<a href="https://colab.research.google.com/github/Juniorexz/Codigo/blob/master/Minera%C3%A7%C3%A3o%20de%20dados%20com%20Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
#data manipulation
import numpy as np
import pandas as pd
import geopandas as gpd

#data visualization
import geobr
import seaborn as sns
import matplotlib.pyplot as plt

In [9]:
#exemplo 1 (lista e tupla)
series = pd.Series([10, 11, 90, 1])

# ou : pd.Series((7, 8, 9, 10,11))

In [10]:
type(series)

pandas.core.series.Series

In [11]:
series #subconjunto dos dados

0    10
1    11
2    90
3     1
dtype: int64

In [12]:
dir(series)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__r

In [13]:
lista_1 = [8,9]
lista_2 = [9,8]

In [14]:
lista_1+lista_2

[8, 9, 9, 8]

In [15]:
vetor_1 = np.array(lista_1)
vetor_2 = np.array(lista_2)


In [16]:
vetor_1+vetor_2

array([17, 17])

In [17]:
vetor_1.mean()

8.5

In [18]:
# exemplço 2 (ndarray)
pd.Series(np.array(['h','i','j','z']), index = [1,2,3,4])

1    h
2    i
3    j
4    z
dtype: object

In [19]:
#(Dicionário)
pd.Series({'a':9, 'b': 1, 'c':10})

a     9
b     1
c    10
dtype: int64

In [3]:
pd.Series(1, index = np.arange(1, 21))

1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
20    1
dtype: int64

In [2]:
#random = Números inteiros aleatórios
#np.random.seed(7) - Com o seed a aleatoriedade vai continuar
data = np.random.randint(low = 1, high = 1000, size = 8)
index = ['a', 'b', 'c', 'd', 'e','f', 'g', 'h']
series = pd.Series(data, index = index)
series

a    441
b    194
c    210
d    820
e    250
f    121
g    204
h    489
dtype: int64

In [20]:
# Os 5 primeiros elementos
series.head()

0    10
1    11
2    90
3     1
dtype: int64

In [16]:
pop install!


SyntaxError: ignored

In [21]:
!pip install Fiona -- quiet

ERROR: Could not find a version that satisfies the requirement quiet (from versions: none)
ERROR: No matching distribution found for quiet


In [ ]:
!pip install Fiona-1.8.20-cp38-cp38-win_amd64 --quiet

In [ ]:
!pip install Fiona-1.8.20-cp310-cp310-win_amd64 -quiet

In [ ]:
!pip install geopandas-0.10.2-py2.py3-none-any -quiet

In [ ]:
!pip install GDAL-3.3.3-cp310-cp310-win_amd64 -quiet

In [ ]:
!pip install geopandas-0.10.2-py2.py3-none-any -quiet

In [ ]:
!pip install geopandas-0.6.2-py2.py3-none-any

In [3]:
geopandas-0.6.2-py2.py3-none-any -quiet

SyntaxError: ignored

In [2]:
!pip install geopandas-0.6.2-py2.py3-none-any -quiet


Usage:   
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

no such option: -u


In [4]:
!pip install geopandas

     |████████████████████████████████| 1.0 MB 24.7 MB/s 
     |████████████████████████████████| 16.7 MB 57.4 MB/s 
     |████████████████████████████████| 6.3 MB 60.6 MB/s 


In [1]:
#data manipulation
import numpy as np
import pandas as pd
import geopandas as gpd

#data visualization
import geobr
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
!pip install geobr

In [5]:
np.random.randint(1, 200, 300)

array([ 24, 123,   8,  62,  22,  20,  94,  18,  31,  21,  98,  40,   3,
       199,  94,  51,   3,  41, 128,  79, 145,  53, 125, 194, 121, 188,
        89,  58,  54, 101,  21, 145,  64,  21,  76, 120,  76, 169, 102,
        60,  37,  76, 123, 160,  48,  23,  72, 182,  28,  90, 131,  37,
        68, 164, 190,  66,  87,  52,  31, 169, 178,  19, 138,  87, 117,
       151, 180, 128,  27, 127,  13,  61,   6,  16, 108, 119, 103,   4,
        95, 101,  31,  41, 175, 112, 113,  86,  27, 147, 186,  15,  38,
        32, 189,  66, 110,  11,  90, 190, 145, 197,  77,  45, 166, 182,
        16, 119, 161,   9,  72, 109, 184, 113,  44,  26, 176,  71, 127,
        24, 190,   1,  44,  92, 185, 103,  32,  80, 104,  79,   9, 136,
       175, 108,  47, 126,  35, 158, 184, 119, 129,  62,  23, 174,  74,
       157, 188,  42,  38,  84, 143, 189, 185,  77, 114, 167,  76,  49,
       170, 116, 175,  89,  71,  86,  76,  40,  56,  67, 104,  28, 193,
       167, 199,  54,  21, 121, 147,  49, 185,   8,   7, 102, 17

In [6]:
np.random.seed(10) #Gera os mesmos números aleatórios
np.random.randint(1, 200, 300)

array([ 10, 126,  16,  65, 114, 124, 157, 158, 114,   9,  74,   1,  41,
       165, 116,  17, 101, 140,  55,  89, 108, 123,  63,  34, 101, 178,
       180,  55,  78, 198,  14, 154, 127, 142,  93,  87,  31, 159,  90,
       141,  66,  32,  58,  37,  28,  19,  94,  78, 151, 152,  95, 140,
       157,  75, 138,  16,  19, 119,  72,  89, 140, 146, 175, 136,  29,
        34,  97,  45, 134,   5,  72,  89,  89,  51, 109, 183,  35, 105,
        16,  89, 144, 135,  86, 151,  12, 113,  13,  63, 186,  80, 109,
        43,  58,  98,  51,  46, 169, 166, 129, 147,  24,   4,  30,  17,
        85,  83, 113,  15,  52,  80,  18, 179,  54, 154, 111, 177,  18,
       161,  82,  42,  91,  13,  31, 146, 145, 129, 160, 102, 193, 125,
       167,  23,  97,  67,  68, 191,  96, 100, 156,  83,  63,  78, 108,
        49, 118, 116, 166,  12, 150, 162,  96, 172,  74, 169, 102, 172,
        91,  72, 137,  73, 157, 110,  31, 124, 154, 191,  14, 170, 162,
         5,  95,  29,  40,  92, 104,  10,   8, 151,  33,   4,  1