<a href="https://colab.research.google.com/github/Juniorexz/Codigo/blob/master/Projeto_Ml_KNN_Euclidiano.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Algoritmo de machine learning usado pra regressão e classificação.Recebe as informações,calcula as distâncias,ordena do menor para o maior,faz uma contagem das classes ,classifica pelos k-vizinhos e define a variavel.
Receber as características da amostra.
Calcular a distância da amostra nova com as amostras já existentes.
Ordenar as distâncias obtidas da menor para a maior.
A partir do número de K vizinhos desejados, escolher quais as características que mais se assemelham.Caso K muito pequeno => Overfitting Os dados vão se ajustar aos dados de entrada.K muito grande => UnderfittingVai haver muitas classes e vai classificar de forma errada.



In [1]:
import pandas as pd

In [2]:
dados = pd.read_csv('/content/Customer-Churn.csv')

In [3]:
#Dados é a quantidade de clientes no caso e 18 são colunas
dados.shape

(7043, 18)

In [4]:
dados.head()

Maior65Anos Conjuge Dependentes  MesesDeContrato TelefoneFixo  \
0            0     Sim         Nao                1          Nao   
1            0     Nao         Nao               34          Sim   
2            0     Nao         Nao                2          Sim   
3            0     Nao         Nao               45          Nao   
4            0     Nao         Nao                2          Sim   

  VariasLinhasTelefonicas ServicoDeInternet SegurancaOnline BackupOnline  \
0    SemServicoTelefonico               DSL             Nao          Sim   
1                     Nao               DSL             Sim          Nao   
2                     Nao               DSL             Sim          Sim   
3    SemServicoTelefonico               DSL             Sim          Nao   
4                     Nao       FibraOptica             Nao          Nao   

  SeguroNoDispositivo SuporteTecnico TVaCabo StreamingDeFilmes TipoDeContrato  \
0                 Nao            Nao     Nao               Nao    Mensalmente   
1                 Sim            Nao     Nao               Nao          UmAno   
2                 Nao            Nao     Nao               Nao    Mensalmente   
3                 Sim            Sim     Nao               Nao          UmAno   
4                 Nao            Nao     Nao               Nao    Mensalmente   

  PagamentoOnline FormaDePagamento  ContaMensal Churn  
0             Sim    ChequeDigital        29.85   Nao  
1             Nao      ChequePapel        56.95   Nao  
2             Sim      ChequePapel        53.85   Sim  
3             Nao    DebitoEmConta        42.30   Nao  
4             Sim    ChequeDigital        70.70   Sim

In [5]:
#Variaveis categoricas e numericar
#Máquina aprende por números,Classificar é o mesmo que transformar as informações dos valores categóricos em algo que a máquina aprenda.

In [6]:
#modificação de forma manual
traducao_dic = {'Sim': 1,
                'Nao': 0}

dadosmodificados = dados[['Conjuge', 'Dependentes', 'TelefoneFixo', 'PagamentoOnline', 'Churn']].replace(traducao_dic)
dadosmodificados.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn
0        1            0             0                1      0
1        0            0             1                0      0
2        0            0             1                1      1
3        0            0             0                0      0
4        0            0             1                1      1

In [7]:
#transformação pelo get_dummies
dummie_dados = pd.get_dummies(dados.drop(['Conjuge', 'Dependentes', 'TelefoneFixo', 'PagamentoOnline', 'Churn'],axis=1))

In [8]:
#junção dos dados transformados como os que já tinham
dados_final = pd.concat([dadosmodificados, dummie_dados], axis=1)

In [9]:
dados_final.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn  Maior65Anos  \
0        1            0             0                1      0            0   
1        0            0             1                0      0            0   
2        0            0             1                1      1            0   
3        0            0             0                0      0            0   
4        0            0             1                1      1            0   

   MesesDeContrato  ContaMensal  VariasLinhasTelefonicas_Nao  \
0                1        29.85                            0   
1               34        56.95                            1   
2                2        53.85                            1   
3               45        42.30                            0   
4                2        70.70                            1   

   VariasLinhasTelefonicas_SemServicoTelefonico  ...  StreamingDeFilmes_Nao  \
0                                             1  ...                      1   
1                                             0  ...                      1   
2                                             0  ...                      1   
3                                             1  ...                      1   
4                                             0  ...                      1   

   StreamingDeFilmes_SemServicoDeInternet  StreamingDeFilmes_Sim  \
0                                       0                      0   
1                                       0                      0   
2                                       0                      0   
3                                       0                      0   
4                                       0                      0   

   TipoDeContrato_DoisAnos  TipoDeContrato_Mensalmente  TipoDeContrato_UmAno  \
0                        0                           1                     0   
1                        0                           0                     1   
2                        0                           1                     0   
3                        0                           0                     1   
4                        0                           1                     0   

   FormaDePagamento_CartaoDeCredito  FormaDePagamento_ChequeDigital  \
0                                 0                               1   
1                                 0                               0   
2                                 0                               0   
3                                 0                               0   
4                                 0                               1   

   FormaDePagamento_ChequePapel  FormaDePagamento_DebitoEmConta  
0                             0                               0  
1                             1                               0  
2                             1                               0  
3                             0                               1  
4                             0                               0  

[5 rows x 39 columns]

In [10]:
dados_final.shape

(7043, 39)

In [11]:
#definição formal = x inputs(dados de entrada),y outputs(dados de saída)

In [12]:
#Dica
pd.set_option('display.max_columns', 39)

In [13]:
dados_final.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn  Maior65Anos  \
0        1            0             0                1      0            0   
1        0            0             1                0      0            0   
2        0            0             1                1      1            0   
3        0            0             0                0      0            0   
4        0            0             1                1      1            0   

   MesesDeContrato  ContaMensal  VariasLinhasTelefonicas_Nao  \
0                1        29.85                            0   
1               34        56.95                            1   
2                2        53.85                            1   
3               45        42.30                            0   
4                2        70.70                            1   

   VariasLinhasTelefonicas_SemServicoTelefonico  VariasLinhasTelefonicas_Sim  \
0                                             1                            0   
1                                             0                            0   
2                                             0                            0   
3                                             1                            0   
4                                             0                            0   

   ServicoDeInternet_DSL  ServicoDeInternet_FibraOptica  \
0                      1                              0   
1                      1                              0   
2                      1                              0   
3                      1                              0   
4                      0                              1   

   ServicoDeInternet_Nao  SegurancaOnline_Nao  \
0                      0                    1   
1                      0                    0   
2                      0                    0   
3                      0                    0   
4                      0                    1   

   SegurancaOnline_SemServicoDeInternet  SegurancaOnline_Sim  \
0                                     0                    0   
1                                     0                    1   
2                                     0                    1   
3                                     0                    1   
4                                     0                    0   

   BackupOnline_Nao  BackupOnline_SemServicoDeInternet  BackupOnline_Sim  \
0                 0                                  0                 1   
1                 1                                  0                 0   
2                 0                                  0                 1   
3                 1                                  0                 0   
4                 1                                  0                 0   

   SeguroNoDispositivo_Nao  SeguroNoDispositivo_SemServicoDeInternet  \
0                        1                                         0   
1                        0                                         0   
2                        1                                         0   
3                        0                                         0   
4                        1                                         0   

   SeguroNoDispositivo_Sim  SuporteTecnico_Nao  \
0                        0                   1   
1                        1                   1   
2                        0                   1   
3                        1                   0   
4                        0                   1   

   SuporteTecnico_SemServicoDeInternet  SuporteTecnico_Sim  TVaCabo_Nao  \
0                                    0                   0            1   
1                                    0                   0            1   
2                                    0                   0            1   
3                                    0                   1            1   
4                                    0                   0         

Existem duas categorias de problemas que podem ser bem resolvidos com a utilização de Machine Learning: os de classificação e os de regressão.

Classificação
Quando precisamos prever a qual categoria pertence uma determinada amostra, trata-se de um problema de classificação. Alguns exemplos que podemos citar são:

Prever se um(a) determinado(a) paciente está com Covid.
Se um(a) cliente está propenso(a) a desistir da compra.
Se algum(a) usuário(a) web está propenso(a) a clicar em um anúncio.
Nesses casos mencionados, a previsão se concentra em 0 ou 1 (Covid/não Covid, desistir/não desistir, clicar/não clicar) que é denominada de classificação binária, na qual existem somente duas classes. Há também casos em que a classificação se dá com mais duas classes, chamada de classificação multiclasse, como a filtragem dos e-mails em “principal”, “social”, “promoções”, “importantes” ou “fóruns”.

Entre os algoritmos de classificação podemos citar:

K-Nearest Neighbors (KNN)
Support Vector Machine (SVM)
Decision Tree Classifier
Random Forest Classifier
Regressão
Quando precisamos prever um valor numérico específico, isso indica que estamos lidando com um problema de regressão. Alguns exemplos desses problemas estão relacionados à previsão de:

preços/custos futuros;
estoque;
receita futura.
Nessas situações, podemos utilizar algum modelo de regressão para realizar essas previsões e apresentar como resposta algum valor contínuo relacionado ao problema. Existem diferentes tipos de algoritmos de machine learning utilizados para resolver esse tipo de problema:

Linear Regression;
Random Forest Regressor;
Support Vector Regression (SVR).
Caso queira aprofundar e conhecer mais sobre algoritmos de regressão, deixamos aqui a indicação de dois cursos que abordam esse assunto:

Regressão Linear: Testando Relações e Prevendo Resultados;
Regressão Linear: Técnicas Avançadas de Modelagem.

Normalização = Mesma escala

In [14]:
Xmaria = [[0,
		  0,
		  1,
		  1,
		  0,
		  0,
		  39.9,
		  1,
		  0,
		  0,
		  0,
		  1,
		  0,
		  1,
		  0,
		  0,
		  0,
		  0,
		  1,
		  1,
		  1,
		  0,
		  0,
		  1,
		  0,
		  1,
		  0,
		  0,
		  0,
		  0,
		  1,
		  0,
		  0,
		  1,
		  0,
		  0,
		  0,
		  1]]

In [15]:
#ymaria = ?

In [16]:
#Divisão em inputs e outputs
X = dados_final.drop('Churn', axis = 1)
Y = dados_final['Churn']

In [17]:
#Biblioteca para padronizar os dados
from sklearn.preprocessing import StandardScaler


In [18]:
norm = StandardScaler()

In [19]:
norm = StandardScaler()

x_normalizado = norm.fit_transform(X)
x_normalizado

array([[ 1.03453023, -0.65401193, -3.05401039, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       ...,
       [ 1.03453023,  1.5290241 , -3.05401039, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [ 1.03453023, -0.65401193,  0.32743831, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ..., -0.71102597,
        -0.54480692,  1.88720123]])

In [20]:
x_normalizado[0]

array([ 1.03453023, -0.65401193, -3.05401039,  0.8297975 , -0.43991649,
       -1.27744458, -1.16032292, -0.96332984,  3.05401039, -0.85417615,
        1.38171215, -0.88565976, -0.52592737,  1.00669571, -0.52592737,
       -0.63393298, -0.88361972, -0.52592737,  1.3782406 ,  1.12942721,
       -0.52592737, -0.72396752,  1.0138687 , -0.52592737, -0.63943864,
        1.2273572 , -0.52592737, -0.79013171,  1.23648892, -0.52592737,
       -0.79607014, -0.56297505,  0.90418382, -0.51424938, -0.52504733,
        1.40641839, -0.54480692, -0.5298852 ])

In [21]:
#Função que só é aplicada quando o conjunto de dados se encontra em duas dimensões(linhas e colunas)
Xmaria_normalizado = norm.transform(pd.DataFrame(Xmaria, columns = X.columns))
Xmaria_normalizado


array([[-0.96662231, -0.65401193,  0.32743831,  0.8297975 , -0.43991649,
        -1.31816495, -0.82630172,  1.03806605, -0.32743831, -0.85417615,
        -0.72373975,  1.12910177, -0.52592737,  1.00669571, -0.52592737,
        -0.63393298, -0.88361972, -0.52592737,  1.3782406 ,  1.12942721,
         1.90140322, -0.72396752, -0.98632101,  1.90140322, -0.63943864,
         1.2273572 , -0.52592737, -0.79013171, -0.80874158, -0.52592737,
         1.25617071, -0.56297505, -1.1059698 ,  1.94458183, -0.52504733,
        -0.71102597, -0.54480692,  1.88720123]])

Métrica de distância euclidiana
Raiz quadrada do somatório de todos os atributos(caracteristicas) elevado ao quadrado

In [22]:
import numpy as np

In [23]:
a = Xmaria_normalizado

In [24]:
b = x_normalizado

In [25]:
#1 - Passo - Começando a subtrair
a - b

array([[-2.00115254,  0.        ,  3.3814487 , ..., -2.11744436,
         0.        ,  2.41708643],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
        -2.38031958,  2.41708643],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
        -2.38031958,  2.41708643],
       ...,
       [-2.00115254, -2.18303603,  3.3814487 , ..., -2.11744436,
         0.        ,  2.41708643],
       [-2.00115254,  0.        ,  0.        , ...,  0.        ,
        -2.38031958,  2.41708643],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [26]:
#2 - Passo - Realizado a exponenciação(Multiplicação feita várias vezes por ele mesmo)
np.square(a-b)

array([[ 4.00461149,  0.        , 11.43419532, ...,  4.48357062,
         0.        ,  5.84230682],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         5.66592128,  5.84230682],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         5.66592128,  5.84230682],
       ...,
       [ 4.00461149,  4.7656463 , 11.43419532, ...,  4.48357062,
         0.        ,  5.84230682],
       [ 4.00461149,  0.        ,  0.        , ...,  0.        ,
         5.66592128,  5.84230682],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [27]:
#3 - a soma
np.sum(np.square(a-b))

540193.8043307611

In [28]:
#4 - É tirado a raiz para se ter a distância(De Maria com a nossa base 0)
np.sqrt(540193.8043307611)

734.978778149928

No algoritmo KNN, para que seja feita a classificação dos registros com base nos vizinhos mais próximos, é necessário utilizar alguma medida para identificar o quão próximo o registro está dos seus vizinhos. Existem diversas medidas para se avaliar essa proximidade entre variáveis numéricas que recebem o nome de medidas de distância. Quanto maior o valor dessa medida, mais distante um elemento está do outro, ou seja, menor a similaridade entre eles.

Considere a tabela a seguir com duas observações e n variáveis para o entendimento das medidas de distância.

Observação	Variável 1	Variável 2	...	Variável n
X	X1	X2	...	Xn
Y	Y1	Y2	...	Yn
Distância Euclidiana
A medida de distância mais conhecida e mais utilizada é a distância euclidiana. Ela consiste em subtrair as coordenadas de uma observação pela outra observação, elevar ao quadrado os resultados, somar todos os valores e extrair a raiz quadrada.

alt text: Fórmula: d igual a raiz quadrada da soma de n termos: O primeiro termo é x 1 menos y 1 ao quadrado. O último termo é x n menos y n ao quadrado. Os termos intermediários da soma estão ocultos e representam os termos de x 2 a x n menos 1 e y 2 a y n menos 1.

Distância de Manhattan
Uma distância que considera apenas a soma dos módulos das diferenças entre cada par de coordenadas.

alt text: Fórmula: d igual a soma de n termos: O primeiro termo é o módulo de x 1 menos y 1. O último termo é o módulo de x n menos y n. Os termos intermediários da soma estão ocultos e representam os termos de x 2 a x n menos 1 e y 2 a y n menos 1.

Distância de Minkowski
Uma medida de distância que é a generalização de outras distâncias, como a distância euclidiana e a de Manhattan. Consiste em extrair o módulo da diferença entre cada par de coordenadas elevando o resultado a m, realizar a soma de todos os termos e, por fim, tirar a raiz m-ésima, em que m é um número qualquer. A distância euclidiana é um caso à parte quando m é igual a 2 e a distância de Manhattan é um caso à parte quando m é igual a 1.

alt text: Fórmula: d igual a raiz m ésima da soma de n termos: O primeiro termo é o módulo de x 1 menos y 1 elevado a m. O último termo é o módulo de x n menos y n elevado a m. Os termos intermediários da soma estão ocultos e representam os termos de x 2 a x n menos 1 e y 2 a y n menos 1.

Distância de Chebyshev
É uma medida de distância que considera apenas o valor máximo entre os módulos das diferenças entre as variáveis. Dessa forma, leva em consideração apenas a variável que possui a maior diferença de valores entre as duas observações.

alt text: Fórmula: d igual ao máximo entre n termos: O primeiro termo é o módulo de x 1 menos y 1. O último termo é o módulo de x n menos y n. Os termos intermediários estão ocultos e representam os termos de x 2 a x n menos 1 e y 2 a y n menos 1.

Existem diversas outras medidas de distância que podem ser calculadas e cada uma delas impacta diretamente no resultado do modelo. As distâncias apresentadas aqui podem ser utilizadas no algoritmo KNN do scikit-learn, sendo a distância de Minkowski a medida de distância padrão ao instanciar o algoritmo, como pode ser checado na documentação.

Podemos modificar a medida de distância utilizando o argumento metric da função sklearn.neighbors.KNeighborsClassifier. Com base nas medidas que foram apresentadas no texto, o parâmetro pode receber os seguintes valores:

“euclidean” para a distância euclidiana;
“manhattan” para a distância de Manhattan;
“minkowski” para a distância de Minkowski;
“chebyshev” para a distância de Chebyshev.
Caso tenha interesse em descobrir o funcionamento ou outras medidas de distância que podem ser utilizadas, confira a documentação do sklearn.metrics.DistanceMetric.

In [29]:
#Biblioteca para divisão dos dados
from sklearn.model_selection import train_test_split

In [30]:
x_treino, x_teste, y_treino, y_teste = train_test_split(x_normalizado, Y, test_size=0.3, random_state=123) 

Treino e Teste

In [31]:
#biblioteca para modelo de machine learning
from sklearn.neighbors import KNeighborsClassifier

In [32]:
#Instanciar modelo(criado o modelo) - padrão 5 vizinhos
knn = KNeighborsClassifier(metric='euclidean')

In [33]:
#Treinando o modelo com dados de treino
knn.fit(x_treino, y_treino)

KNeighborsClassifier(metric='euclidean')

In [34]:
#Testando o modelo com os dados de teste
predito_knn = knn.predict(x_teste)

In [35]:
predito_knn

array([1, 0, 0, ..., 0, 0, 0])

Calcule a distância da Maria com os(as) 10 primeiros(as) clientes da nossa base de dados normalizada utilizando a métrica euclidiana.


In [36]:
import numpy as np

In [37]:
#Depois, podemos construir uma função para calcular todas as distâncias de uma vez.
def calcula_distancia(dados_clientes, dados_maria, numero_clientes):
    distancias = []

#loop para percorrer cliente por cliente
    for i in range(numero_clientes):
        dist1 = dados_maria - dados_clientes[i]            #subtração dos atributos
        soma_quadrado = np.sum(np.square(dist1))    #exponenciação e soma de todos os atributos
        distancias.append(np.sqrt(soma_quadrado))   #raiz quadrada da soma anterior

    return distancias

In [38]:
calcula_distancia(x_normalizado, Xmaria_normalizado, 10)

[9.169282435541762,
 8.742314068192332,
 7.96104771727276,
 9.683687116435184,
 7.35756725091328,
 8.58650261645753,
 8.411628863624525,
 10.145869884558158,
 8.97159048640628,
 7.5587041367106105]

In [39]:
x_treino

array([[-0.96662231, -0.65401193, -3.05401039, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [-0.96662231,  1.5290241 ,  0.32743831, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       ...,
       [ 1.03453023,  1.5290241 ,  0.32743831, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [ 1.03453023,  1.5290241 , -3.05401039, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ...,  1.40641839,
        -0.54480692, -0.5298852 ]])

In [40]:
y_treino

1479    0
2377    0
6613    0
6468    0
2668    1
       ..
5218    0
4060    0
1346    1
3454    0
3582    0
Name: Churn, Length: 4930, dtype: int64

In [41]:
#Se utiliza mediana pois é o valor central dos dados ordenados
np.median(x_treino)

-0.5259273725834717

In [42]:
#Biblioteca pra criar o machine learning
from sklearn.naive_bayes import BernoulliNB

In [43]:
#Criando o modelo,binarize = define o limite para transformar a variavel em binário ou não,valores acima do binarize = 1 , abixo = 0
bnb = BernoulliNB(binarize=-0.52)

In [44]:
bnb.fit(x_treino, y_treino)

BernoulliNB(binarize=-0.52)

In [46]:
predito_BNb = bnb.predict(x_teste)

In [47]:
predito_BNb

array([1, 0, 0, ..., 0, 1, 0])