<a href="https://colab.research.google.com/github/Juniorexz/Codigo/blob/master/Projeto_Ml_KNN_Euclidiano%20-%20DecisionTreev-Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Algoritmo de machine learning usado pra regressão e classificação.Recebe as informações,calcula as distâncias,ordena do menor para o maior,faz uma contagem das classes ,classifica pelos k-vizinhos e define a variavel.
Receber as características da amostra.
Calcular a distância da amostra nova com as amostras já existentes.
Ordenar as distâncias obtidas da menor para a maior.
A partir do número de K vizinhos desejados, escolher quais as características que mais se assemelham.Caso K muito pequeno => Overfitting Os dados vão se ajustar aos dados de entrada.K muito grande => UnderfittingVai haver muitas classes e vai classificar de forma errada.



In [1]:
import pandas as pd

In [2]:
dados = pd.read_csv('/content/Customer-Churn.csv')

In [3]:
#Dados é a quantidade de clientes no caso e 18 são colunas
dados.shape

(7043, 18)

In [4]:
dados.head()

Maior65Anos Conjuge Dependentes  MesesDeContrato TelefoneFixo  \
0            0     Sim         Nao                1          Nao   
1            0     Nao         Nao               34          Sim   
2            0     Nao         Nao                2          Sim   
3            0     Nao         Nao               45          Nao   
4            0     Nao         Nao                2          Sim   

  VariasLinhasTelefonicas ServicoDeInternet SegurancaOnline BackupOnline  \
0    SemServicoTelefonico               DSL             Nao          Sim   
1                     Nao               DSL             Sim          Nao   
2                     Nao               DSL             Sim          Sim   
3    SemServicoTelefonico               DSL             Sim          Nao   
4                     Nao       FibraOptica             Nao          Nao   

  SeguroNoDispositivo SuporteTecnico TVaCabo StreamingDeFilmes TipoDeContrato  \
0                 Nao            Nao     Nao               Nao    Mensalmente   
1                 Sim            Nao     Nao               Nao          UmAno   
2                 Nao            Nao     Nao               Nao    Mensalmente   
3                 Sim            Sim     Nao               Nao          UmAno   
4                 Nao            Nao     Nao               Nao    Mensalmente   

  PagamentoOnline FormaDePagamento  ContaMensal Churn  
0             Sim    ChequeDigital        29.85   Nao  
1             Nao      ChequePapel        56.95   Nao  
2             Sim      ChequePapel        53.85   Sim  
3             Nao    DebitoEmConta        42.30   Nao  
4             Sim    ChequeDigital        70.70   Sim

In [5]:
#Variaveis categoricas e numericar
#Máquina aprende por números,Classificar é o mesmo que transformar as informações dos valores categóricos em algo que a máquina aprenda.

In [6]:
#modificação de forma manual
traducao_dic = {'Sim': 1,
                'Nao': 0}

dadosmodificados = dados[['Conjuge', 'Dependentes', 'TelefoneFixo', 'PagamentoOnline', 'Churn']].replace(traducao_dic)
dadosmodificados.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn
0        1            0             0                1      0
1        0            0             1                0      0
2        0            0             1                1      1
3        0            0             0                0      0
4        0            0             1                1      1

In [7]:
#transformação pelo get_dummies
dummie_dados = pd.get_dummies(dados.drop(['Conjuge', 'Dependentes', 'TelefoneFixo', 'PagamentoOnline', 'Churn'],axis=1))

In [8]:
#junção dos dados transformados como os que já tinham
dados_final = pd.concat([dadosmodificados, dummie_dados], axis=1)

In [9]:
dados_final.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn  Maior65Anos  \
0        1            0             0                1      0            0   
1        0            0             1                0      0            0   
2        0            0             1                1      1            0   
3        0            0             0                0      0            0   
4        0            0             1                1      1            0   

   MesesDeContrato  ContaMensal  VariasLinhasTelefonicas_Nao  \
0                1        29.85                            0   
1               34        56.95                            1   
2                2        53.85                            1   
3               45        42.30                            0   
4                2        70.70                            1   

   VariasLinhasTelefonicas_SemServicoTelefonico  ...  StreamingDeFilmes_Nao  \
0                                             1  ...                      1   
1                                             0  ...                      1   
2                                             0  ...                      1   
3                                             1  ...                      1   
4                                             0  ...                      1   

   StreamingDeFilmes_SemServicoDeInternet  StreamingDeFilmes_Sim  \
0                                       0                      0   
1                                       0                      0   
2                                       0                      0   
3                                       0                      0   
4                                       0                      0   

   TipoDeContrato_DoisAnos  TipoDeContrato_Mensalmente  TipoDeContrato_UmAno  \
0                        0                           1                     0   
1                        0                           0                     1   
2                        0                           1                     0   
3                        0                           0                     1   
4                        0                           1                     0   

   FormaDePagamento_CartaoDeCredito  FormaDePagamento_ChequeDigital  \
0                                 0                               1   
1                                 0                               0   
2                                 0                               0   
3                                 0                               0   
4                                 0                               1   

   FormaDePagamento_ChequePapel  FormaDePagamento_DebitoEmConta  
0                             0                               0  
1                             1                               0  
2                             1                               0  
3                             0                               1  
4                             0                               0  

[5 rows x 39 columns]

In [10]:
dados_final.shape

(7043, 39)

In [11]:
#definição formal = x inputs(dados de entrada),y outputs(dados de saída)

In [12]:
#Dica
pd.set_option('display.max_columns', 39)

In [13]:
dados_final.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn  Maior65Anos  \
0        1            0             0                1      0            0   
1        0            0             1                0      0            0   
2        0            0             1                1      1            0   
3        0            0             0                0      0            0   
4        0            0             1                1      1            0   

   MesesDeContrato  ContaMensal  VariasLinhasTelefonicas_Nao  \
0                1        29.85                            0   
1               34        56.95                            1   
2                2        53.85                            1   
3               45        42.30                            0   
4                2        70.70                            1   

   VariasLinhasTelefonicas_SemServicoTelefonico  VariasLinhasTelefonicas_Sim  \
0                                             1                            0   
1                                             0                            0   
2                                             0                            0   
3                                             1                            0   
4                                             0                            0   

   ServicoDeInternet_DSL  ServicoDeInternet_FibraOptica  \
0                      1                              0   
1                      1                              0   
2                      1                              0   
3                      1                              0   
4                      0                              1   

   ServicoDeInternet_Nao  SegurancaOnline_Nao  \
0                      0                    1   
1                      0                    0   
2                      0                    0   
3                      0                    0   
4                      0                    1   

   SegurancaOnline_SemServicoDeInternet  SegurancaOnline_Sim  \
0                                     0                    0   
1                                     0                    1   
2                                     0                    1   
3                                     0                    1   
4                                     0                    0   

   BackupOnline_Nao  BackupOnline_SemServicoDeInternet  BackupOnline_Sim  \
0                 0                                  0                 1   
1                 1                                  0                 0   
2                 0                                  0                 1   
3                 1                                  0                 0   
4                 1                                  0                 0   

   SeguroNoDispositivo_Nao  SeguroNoDispositivo_SemServicoDeInternet  \
0                        1                                         0   
1                        0                                         0   
2                        1                                         0   
3                        0                                         0   
4                        1                                         0   

   SeguroNoDispositivo_Sim  SuporteTecnico_Nao  \
0                        0                   1   
1                        1                   1   
2                        0                   1   
3                        1                   0   
4                        0                   1   

   SuporteTecnico_SemServicoDeInternet  SuporteTecnico_Sim  TVaCabo_Nao  \
0                                    0                   0            1   
1                                    0                   0            1   
2                                    0                   0            1   
3                                    0                   1            1   
4                                    0                   0         

Existem duas categorias de problemas que podem ser bem resolvidos com a utilização de Machine Learning: os de classificação e os de regressão.

Classificação
Quando precisamos prever a qual categoria pertence uma determinada amostra, trata-se de um problema de classificação. Alguns exemplos que podemos citar são:

Prever se um(a) determinado(a) paciente está com Covid.
Se um(a) cliente está propenso(a) a desistir da compra.
Se algum(a) usuário(a) web está propenso(a) a clicar em um anúncio.
Nesses casos mencionados, a previsão se concentra em 0 ou 1 (Covid/não Covid, desistir/não desistir, clicar/não clicar) que é denominada de classificação binária, na qual existem somente duas classes. Há também casos em que a classificação se dá com mais duas classes, chamada de classificação multiclasse, como a filtragem dos e-mails em “principal”, “social”, “promoções”, “importantes” ou “fóruns”.

Entre os algoritmos de classificação podemos citar:

K-Nearest Neighbors (KNN)
Support Vector Machine (SVM)
Decision Tree Classifier
Random Forest Classifier
Regressão
Quando precisamos prever um valor numérico específico, isso indica que estamos lidando com um problema de regressão. Alguns exemplos desses problemas estão relacionados à previsão de:

preços/custos futuros;
estoque;
receita futura.
Nessas situações, podemos utilizar algum modelo de regressão para realizar essas previsões e apresentar como resposta algum valor contínuo relacionado ao problema. Existem diferentes tipos de algoritmos de machine learning utilizados para resolver esse tipo de problema:

Linear Regression;
Random Forest Regressor;
Support Vector Regression (SVR).
Caso queira aprofundar e conhecer mais sobre algoritmos de regressão, deixamos aqui a indicação de dois cursos que abordam esse assunto:

Regressão Linear: Testando Relações e Prevendo Resultados;
Regressão Linear: Técnicas Avançadas de Modelagem.

Normalização = Mesma escala

In [14]:
Xmaria = [[0,
		  0,
		  1,
		  1,
		  0,
		  0,
		  39.9,
		  1,
		  0,
		  0,
		  0,
		  1,
		  0,
		  1,
		  0,
		  0,
		  0,
		  0,
		  1,
		  1,
		  1,
		  0,
		  0,
		  1,
		  0,
		  1,
		  0,
		  0,
		  0,
		  0,
		  1,
		  0,
		  0,
		  1,
		  0,
		  0,
		  0,
		  1]]

In [15]:
#ymaria = ?

In [16]:
#Divisão em inputs e outputs
X = dados_final.drop('Churn', axis = 1)
Y = dados_final['Churn']

In [17]:
#Biblioteca para padronizar os dados
from sklearn.preprocessing import StandardScaler


In [18]:
norm = StandardScaler()

In [19]:
norm = StandardScaler()

x_normalizado = norm.fit_transform(X)
x_normalizado

array([[ 1.03453023, -0.65401193, -3.05401039, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       ...,
       [ 1.03453023,  1.5290241 , -3.05401039, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [ 1.03453023, -0.65401193,  0.32743831, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ..., -0.71102597,
        -0.54480692,  1.88720123]])

In [20]:
x_normalizado[0]

array([ 1.03453023, -0.65401193, -3.05401039,  0.8297975 , -0.43991649,
       -1.27744458, -1.16032292, -0.96332984,  3.05401039, -0.85417615,
        1.38171215, -0.88565976, -0.52592737,  1.00669571, -0.52592737,
       -0.63393298, -0.88361972, -0.52592737,  1.3782406 ,  1.12942721,
       -0.52592737, -0.72396752,  1.0138687 , -0.52592737, -0.63943864,
        1.2273572 , -0.52592737, -0.79013171,  1.23648892, -0.52592737,
       -0.79607014, -0.56297505,  0.90418382, -0.51424938, -0.52504733,
        1.40641839, -0.54480692, -0.5298852 ])

In [21]:
#Função que só é aplicada quando o conjunto de dados se encontra em duas dimensões(linhas e colunas)
Xmaria_normalizado = norm.transform(pd.DataFrame(Xmaria, columns = X.columns))
Xmaria_normalizado


array([[-0.96662231, -0.65401193,  0.32743831,  0.8297975 , -0.43991649,
        -1.31816495, -0.82630172,  1.03806605, -0.32743831, -0.85417615,
        -0.72373975,  1.12910177, -0.52592737,  1.00669571, -0.52592737,
        -0.63393298, -0.88361972, -0.52592737,  1.3782406 ,  1.12942721,
         1.90140322, -0.72396752, -0.98632101,  1.90140322, -0.63943864,
         1.2273572 , -0.52592737, -0.79013171, -0.80874158, -0.52592737,
         1.25617071, -0.56297505, -1.1059698 ,  1.94458183, -0.52504733,
        -0.71102597, -0.54480692,  1.88720123]])

Métrica de distância euclidiana
Raiz quadrada do somatório de todos os atributos(caracteristicas) elevado ao quadrado

In [22]:
import numpy as np

In [23]:
a = Xmaria_normalizado

In [24]:
b = x_normalizado

In [25]:
#1 - Passo - Começando a subtrair
a - b

array([[-2.00115254,  0.        ,  3.3814487 , ..., -2.11744436,
         0.        ,  2.41708643],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
        -2.38031958,  2.41708643],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
        -2.38031958,  2.41708643],
       ...,
       [-2.00115254, -2.18303603,  3.3814487 , ..., -2.11744436,
         0.        ,  2.41708643],
       [-2.00115254,  0.        ,  0.        , ...,  0.        ,
        -2.38031958,  2.41708643],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [26]:
#2 - Passo - Realizado a exponenciação(Multiplicação feita várias vezes por ele mesmo)
np.square(a-b)

array([[ 4.00461149,  0.        , 11.43419532, ...,  4.48357062,
         0.        ,  5.84230682],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         5.66592128,  5.84230682],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         5.66592128,  5.84230682],
       ...,
       [ 4.00461149,  4.7656463 , 11.43419532, ...,  4.48357062,
         0.        ,  5.84230682],
       [ 4.00461149,  0.        ,  0.        , ...,  0.        ,
         5.66592128,  5.84230682],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [27]:
#3 - a soma
np.sum(np.square(a-b))

540193.8043307611

In [28]:
#4 - É tirado a raiz para se ter a distância(De Maria com a nossa base 0)
np.sqrt(540193.8043307611)

734.978778149928

No algoritmo KNN, para que seja feita a classificação dos registros com base nos vizinhos mais próximos, é necessário utilizar alguma medida para identificar o quão próximo o registro está dos seus vizinhos. Existem diversas medidas para se avaliar essa proximidade entre variáveis numéricas que recebem o nome de medidas de distância. Quanto maior o valor dessa medida, mais distante um elemento está do outro, ou seja, menor a similaridade entre eles.

Considere a tabela a seguir com duas observações e n variáveis para o entendimento das medidas de distância.

Observação	Variável 1	Variável 2	...	Variável n
X	X1	X2	...	Xn
Y	Y1	Y2	...	Yn
Distância Euclidiana
A medida de distância mais conhecida e mais utilizada é a distância euclidiana. Ela consiste em subtrair as coordenadas de uma observação pela outra observação, elevar ao quadrado os resultados, somar todos os valores e extrair a raiz quadrada.

alt text: Fórmula: d igual a raiz quadrada da soma de n termos: O primeiro termo é x 1 menos y 1 ao quadrado. O último termo é x n menos y n ao quadrado. Os termos intermediários da soma estão ocultos e representam os termos de x 2 a x n menos 1 e y 2 a y n menos 1.

Distância de Manhattan
Uma distância que considera apenas a soma dos módulos das diferenças entre cada par de coordenadas.

alt text: Fórmula: d igual a soma de n termos: O primeiro termo é o módulo de x 1 menos y 1. O último termo é o módulo de x n menos y n. Os termos intermediários da soma estão ocultos e representam os termos de x 2 a x n menos 1 e y 2 a y n menos 1.

Distância de Minkowski
Uma medida de distância que é a generalização de outras distâncias, como a distância euclidiana e a de Manhattan. Consiste em extrair o módulo da diferença entre cada par de coordenadas elevando o resultado a m, realizar a soma de todos os termos e, por fim, tirar a raiz m-ésima, em que m é um número qualquer. A distância euclidiana é um caso à parte quando m é igual a 2 e a distância de Manhattan é um caso à parte quando m é igual a 1.

alt text: Fórmula: d igual a raiz m ésima da soma de n termos: O primeiro termo é o módulo de x 1 menos y 1 elevado a m. O último termo é o módulo de x n menos y n elevado a m. Os termos intermediários da soma estão ocultos e representam os termos de x 2 a x n menos 1 e y 2 a y n menos 1.

Distância de Chebyshev
É uma medida de distância que considera apenas o valor máximo entre os módulos das diferenças entre as variáveis. Dessa forma, leva em consideração apenas a variável que possui a maior diferença de valores entre as duas observações.

alt text: Fórmula: d igual ao máximo entre n termos: O primeiro termo é o módulo de x 1 menos y 1. O último termo é o módulo de x n menos y n. Os termos intermediários estão ocultos e representam os termos de x 2 a x n menos 1 e y 2 a y n menos 1.

Existem diversas outras medidas de distância que podem ser calculadas e cada uma delas impacta diretamente no resultado do modelo. As distâncias apresentadas aqui podem ser utilizadas no algoritmo KNN do scikit-learn, sendo a distância de Minkowski a medida de distância padrão ao instanciar o algoritmo, como pode ser checado na documentação.

Podemos modificar a medida de distância utilizando o argumento metric da função sklearn.neighbors.KNeighborsClassifier. Com base nas medidas que foram apresentadas no texto, o parâmetro pode receber os seguintes valores:

“euclidean” para a distância euclidiana;
“manhattan” para a distância de Manhattan;
“minkowski” para a distância de Minkowski;
“chebyshev” para a distância de Chebyshev.
Caso tenha interesse em descobrir o funcionamento ou outras medidas de distância que podem ser utilizadas, confira a documentação do sklearn.metrics.DistanceMetric.

In [29]:
#Biblioteca para divisão dos dados
from sklearn.model_selection import train_test_split

In [30]:
x_treino, x_teste, y_treino, y_teste = train_test_split(x_normalizado, Y, test_size=0.3, random_state=123) 

Treino e Teste

In [31]:
#biblioteca para modelo de machine learning
from sklearn.neighbors import KNeighborsClassifier

In [32]:
#Instanciar modelo(criado o modelo) - padrão 5 vizinhos
knn = KNeighborsClassifier(metric='euclidean')

In [33]:
#Treinando o modelo com dados de treino
knn.fit(x_treino, y_treino)

KNeighborsClassifier(metric='euclidean')

In [34]:
#Testando o modelo com os dados de teste
predito_knn = knn.predict(x_teste)

In [35]:
predito_knn

array([1, 0, 0, ..., 0, 0, 0])

Calcule a distância da Maria com os(as) 10 primeiros(as) clientes da nossa base de dados normalizada utilizando a métrica euclidiana.


In [36]:
import numpy as np

In [37]:
#Depois, podemos construir uma função para calcular todas as distâncias de uma vez.
def calcula_distancia(dados_clientes, dados_maria, numero_clientes):
    distancias = []

#loop para percorrer cliente por cliente
    for i in range(numero_clientes):
        dist1 = dados_maria - dados_clientes[i]            #subtração dos atributos
        soma_quadrado = np.sum(np.square(dist1))    #exponenciação e soma de todos os atributos
        distancias.append(np.sqrt(soma_quadrado))   #raiz quadrada da soma anterior

    return distancias

In [38]:
calcula_distancia(x_normalizado, Xmaria_normalizado, 10)

[9.169282435541762,
 8.742314068192332,
 7.96104771727276,
 9.683687116435184,
 7.35756725091328,
 8.58650261645753,
 8.411628863624525,
 10.145869884558158,
 8.97159048640628,
 7.5587041367106105]

In [39]:
x_treino

array([[-0.96662231, -0.65401193, -3.05401039, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [-0.96662231,  1.5290241 ,  0.32743831, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       ...,
       [ 1.03453023,  1.5290241 ,  0.32743831, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [ 1.03453023,  1.5290241 , -3.05401039, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ...,  1.40641839,
        -0.54480692, -0.5298852 ]])

In [40]:
y_treino

1479    0
2377    0
6613    0
6468    0
2668    1
       ..
5218    0
4060    0
1346    1
3454    0
3582    0
Name: Churn, Length: 4930, dtype: int64

In [41]:
#Se utiliza mediana pois é o valor central dos dados ordenados
np.median(x_treino)

-0.5259273725834717

In [42]:
#Biblioteca pra criar o machine learning
from sklearn.naive_bayes import BernoulliNB

In [43]:
#Criando o modelo,binarize = define o limite para transformar a variavel em binário ou não,valores acima do binarize = 1 , abixo = 0
bnb = BernoulliNB(binarize=-0.52)

In [44]:
bnb.fit(x_treino, y_treino)

BernoulliNB(binarize=-0.52)

In [45]:
predito_BNb = bnb.predict(x_teste)

In [46]:
predito_BNb

array([1, 0, 0, ..., 0, 1, 0])

Os principais critérios de divisão dos nós, são os seguintes: temos o índice Gini, o Qui-Quadrado, o Ganho de informação (entropia) e a Redução na variância. Os mais utilizados e que eu escolhi para trabalharmos com eles, é o índice Gini e o Ganho de informação, a entropia. Eles são os critérios mais utilizados e mais conhecidos, estou dando uma atenção maior a eles. Eis o índice Gini e esse cálculo de entropia.Primeiro o Índice Gini. Aqui temos a seguinte fórmula: temos o G que é de Gini, igual ao somatório da nossa probabilidade de uma classe ocorrer, vezes ou menos a probabilidade da classe ocorrer. Como assim probabilidade da classe ocorrer?Esse Pk é a probabilidade de ocorrência de um dado da classe K. Temos o exemplo da Maria, meses de contrato maior que 50. Meses de contrato é o atributo, ele pode ser maior que 50 ou menor que 50, são os conjuntos resultantes, as classes resultantes desse dado. Calculando a probabilidade de ocorrência para cada um desses valores, a probabilidade de ocorrer meses de contrato maior que 50 dividido pela ocorrência de todos os dados, todos os atributos, todas essas características, a ocorrência total dos meses de contrato. E da mesma forma para os meses de contrato menor que 50. Pegando essa probabilidade e multiplicar pela probabilidade de não ocorrência de um dado da classe K. Calculando essa probabilidade de qual é a chance da Maria ter meses de contrato maior que 50 entre todas as possibilidades, todas as ocorrências da nossa amostra dos nossos conjuntos de informações. 1 menos isso seria a probabilidade de não ocorrência. O cálculo final vai ser calculado essa probabilidade vezes a probabilidade de não ocorrência de cada uma dessas classes e somar os resultados. Vai pegar o resultado de meses de contrato maior que 50, meses de contrato menor que 50 e vai resultar em um valor. No caso do índice Gini, a ideia é medir o quão impuro está o dado, o quão heterogêneo ele está. Quando o resultado for próximo de 1, quanto maior o resultado mais heterogêneo o dado está, mais difícil de extrair informações, conseguir dividir este dado em diferentes classes. Agora, quanto menor mais homogêneo que seria o ideal. Se aplicarmos esse Índice Gini nos nossos atributos para decidir qual que é o nó raiz, aquele atributo que apresentar o menor Índice Gini vai ser o selecionado para começar a nossa árvore de decisão, é mais homogêneo. Agora, vamos para a entropia, como que a entropia funciona e qual é a ideia de calcular a entropia. A entropia mede a ordem dos dados, de certa forma a entropia e o Índice Gini é semelhante, até por isso que os dois são usados como critérios para verificar a impureza. Mas a entropia foca no ganho de informação, até outro nome conhecido e bem familiar que você pode encontrar por aí nos materiais. A entropia vai medir, falamos de desordem, se um dado está muito desordenado, ele está impuro. Vai ser mais difícil conseguir dividir esses dados ou extrair alguma informação dele. A entropia vai calcular esse ganho de informação, quanto maior a entropia mais desordenado está o dado e quanto menor mais ordenado está, maior ganho de informação. E ele é calculado da seguinte forma: menos o somatório, novamente, da probabilidade da ocorrência daquela classe, vezes o log da probabilidade da ocorrência daquela classe na base dois.Esse Pk é a mesma coisa do Índice Gini, qual a probabilidade de ocorrer, meses de contrato maior que 50. Vai ser meses de contrato dividido pela quantidade total de ocorrências na nossa amostra. Essa vai ser a probabilidade, aí vai multiplicar pelo log dessa probabilidade na base dois.Vai ser calculada para maior que 50 meses de contrato e menor que 50. Então, é realizado o somatório desses resultados obtendo a entropia. E da mesma forma que o Índice Gini é feito de forma recursiva, aplicando em todos os atributos e assim a nossa árvore crescendo e se estruturando.
Se você está se sentindo doente, mas não faz ideia do que possa ser, quando você vai ao médico são feitas uma série de perguntas (dor de cabeça? febre? tosse?...). Ao final da série de perguntas realizadas pelo médico é emitido um parecer informando qual a causa dos sintomas. Nessa situação apresentada foi seguido o mesmo princípio utilizado em um estimador chamado árvore de decisão.

Árvore de decisão é um dos modelos de previsão mais simples, inspirada na forma que os seres humanos tomam as decisões e tem uma alta interpretabilidade, ou seja, uma compreensão fácil dos passos que foram realizados para conseguir chegar ao resultado final. Ela pode ser utilizada tanto para modelos de regressão, que têm intuito de prever valores numéricos, quanto para modelos de classificação, que têm intuito de prever categorias.

Graficamente, a árvore de decisão pode ser representada de forma que cada uma das decisões tomadas no processo possam ser visualizadas. Seus elementos principais são os nós, ramos e folhas. A estrutura da árvore se inicia com um nó inicial, também chamado de raiz. A partir dela são traçadas ramificações, que geram novos nós e o processo se repete para os nós subsequentes até que chegue a uma folha, que se trata de um nó especial que tem a informação da resposta, sendo ela uma categoria ou um valor previsto.

Cada ramo representa uma tomada de decisão a partir de um valor ou de uma categoria das variáveis explicativas, dividindo o conjunto de dados em nós que apresentam dados com características cada vez mais similares entre si.

Para que fiquem mais compreensíveis esses conceitos, vamos a um exemplo.

alt text: Quadro com fundo cinza contendo os sintomas da Covid-19 e um fluxograma com orientações sobre o que fazer em caso de contaminação ou contato com pessoas diagnosticadas com Covid.



Na imagem de exemplo, temos uma orientação sobre Covid-19 para que as pessoas sejam direcionadas a ficarem isoladas ou não. A raiz ou nó inicial representa a pergunta se a pessoa está com sintomas de Covid-19, como aquelas perguntas realizadas pelo médico indicadas no início desse texto. A pergunta é respondida através dos ramos que partem da raiz, separando as pessoas que possuem sintomas das pessoas que não possuem sintomas.

O nó referente às pessoas que possuem sintomas se trata de um nó folha, com a decisão final de isolamento social. O nó referente às pessoas que não possuem sintomas se trata de um nó interno, que passa por um novo questionamento, criando assim novos ramos e nós. O processo se repete até que se chegue em decisões finais.

Portanto, o esquema se trata de uma Árvore de Decisão, em que é possível detectar todas as escolhas que foram feitas para se chegar às conclusões finais. O algoritmo de computador seguirá esses mesmos princípios, tomando as decisões com base nas variáveis explicativas.

Critério de divisão dos nós
Para conseguir identificar qual o melhor momento em que um nó deve ser dividido em dois ou mais subnós, o algoritmo da árvore de decisão considera alguns critérios. Os dois principais critérios de divisão usados nas árvores de decisão são:

Índice Gini
Este índice informa o grau de heterogeneidade dos dados. O objetivo dele é medir a frequência de um elemento aleatório de um nó ser rotulado de maneira incorreta. Em outros termos, esse índice é capaz de medir a impureza de um nó e ele é determinado por meio do seguinte cálculo:

alt text: Fórmula: Gini é igual a 1 menos somatório de i começando em 1 indo até K de P de i ao quadrado.

Onde:

pi representa a frequência relativa das classes em cada um dos nós;
k é o número de classes.
Se o índice Gini for igual a 0, isso indica que o nó é puro. No entanto, se o valor dele se aproxima mais do valor 1, o nó é impuro.

Entropia
A ideia básica da entropia é medir a desordem dos dados de um nó por meio da variável classificadora. Assim como o índice de Gini, ela é utilizada para caracterizar a impureza dos dados e pode ser calculada por meio da seguinte fórmula:

Alt text: Fórmula: Entropia de S, com S entre parênteses, é igual ao somatório de i iniciando em 1 até c de menos p subscrito i vezes o log 2 de p subscrito i.

Onde:

pi representa a proporção de dados no conjunto de dados (S), pertencentes à classe específica i;
c é o número de classes.



Implementando modelo

In [47]:
#Biblioteca Machine Learning
from sklearn.tree import DecisionTreeClassifier

In [48]:
from sklearn.neighbors import KNeighborsClassifier

In [49]:
#Instanciando o modelo
dtc = DecisionTreeClassifier(criterion='entropy', random_state=42)

In [50]:
#Treinar modelo
dtc.fit(x_treino, y_treino)

DecisionTreeClassifier(criterion='entropy', random_state=42)

In [51]:
#Verificar a importância de cada atributo
dtc.feature_importances_

array([0.03168742, 0.01862901, 0.00064085, 0.02675693, 0.0208788 ,
       0.2056003 , 0.29546501, 0.0061786 , 0.00273035, 0.00747536,
       0.        , 0.04908356, 0.        , 0.01609395, 0.        ,
       0.00722833, 0.01220706, 0.        , 0.01248286, 0.01138295,
       0.0006673 , 0.0095669 , 0.01841631, 0.        , 0.00650511,
       0.00385849, 0.        , 0.00666929, 0.00517146, 0.        ,
       0.00665371, 0.00473251, 0.15803541, 0.00348686, 0.01414378,
       0.01601964, 0.01064163, 0.01091026])

In [52]:
predito_ArvoreDecisao = dtc.predict(x_teste)

In [53]:
predito_ArvoreDecisao

array([1, 0, 0, ..., 1, 0, 0])

Primeira coluna, temos o "SIM". Segunda coluna, o "NÃO". Primeira linha, "SIM", segunda linha, "NÃO". As colunas representam os resultados preditos e as linhas representam os valores reais, aqueles que realmente são. Como funciona a matriz de confusão, quais são as visões que ela traz? Ela traz os nossos resultados. Vamos começar aqui na primeira coluna e na primeira linha. Temos o "SIM", foi predito um valor "SIM" e o valor real realmente era "SIM". Qual é o resultado disso? É um verdadeiro positivo, é um verdadeiro sim. Temos o Churn, a Maria foi classificada como "SIM". Estava lá que realmente é um "SIM". Esse é o verdadeiro positivo, são os resultados verdadeiramente corretos, como "SIM". Agora vamos para a segunda visão dos nossos resultados.Vamos para a segunda coluna, primeira linha. Temos o predito como o valor "NÃO", porém, o real é o "SIM". Esse resultado é conhecido como falso negativo ou um falso não, ele deveria ser predito como "SIM", mas ele foi predito como "NÃO". É um valor incorreto da nossa classificação, são aqueles resultados errôneos. Agora podemos passar para a segunda linha. Vamos lá. Primeira coluna, segunda linha. Foi um predito que o valor é um "SIM", contudo, o verdadeiro valor é um "NÃO".O que isso quer dizer? Isso quer dizer que o Churn foi previsto como "SIM", só que o valor dele real é "NÃO". Temos um resultado falso positivo, ou seja, um falso sim, aquele Churn que foi visto como "SIM", mas, na verdade, ele é um "NÃO". São os resultados também errados, são os resultados errôneos da nossa classificação. Agora segunda coluna, segunda linha. Temos o predito como "NÃO" e o real como "NÃO.São aqueles valores que são os verdadeiros negativos, são os valores realmente preditos com "NÃO" e são realmente "NÃO". Foi um Churn previsto como "NÃO" e ele realmente é um "NÃO". Outro valor previsto de forma correta. Nossos valores verdadeiros, positivo e verdadeiro negativo são os valores previstos de forma correta no nosso modelo. Agora entendemos como que é estruturada a matriz de confusão, como ela funciona.

In [54]:
from sklearn.metrics import confusion_matrix


In [55]:
print(confusion_matrix(y_teste, predito_knn))

[[1302  221]
 [ 317  273]]


In [56]:
print(confusion_matrix(y_teste, predito_BNb))

[[1045  478]
 [ 117  473]]


In [57]:
print(confusion_matrix(y_teste, predito_ArvoreDecisao))

[[1249  274]
 [ 290  300]]


Métrica de acurácia =  a acurácia mede o quanto o nosso modelo acertou do total, do total de resultados o quanto que ela acertou.
Temos a seguinte conta: a acurácia vai ser igual aos verdadeiros positivos mais os verdadeiros negativos. Você lembra da matriz de confusão? São os valores realmente corretos, os verdadeiros sins e os verdadeiros nãos no nosso Churn. Dividido por todos os resultados, os verdadeiros positivos mais os falsos positivos, mais os verdadeiros negativos mais os falsos negativos, resultando no total de valores inferidos de forma correta, classificados previstos de forma correta, "ACC = TP + TN/TP + FP + TN + FN".
Para fazer o cálculo da acurácia vamos chamar o pacote métrico da biblioteca SKLearn e a função accuracy. from sklearn,metrics import accuracy_score. Vamos rodar e ok, as funções estão carregadas. Vamos ver a acurácia do nosso primeiro modelo, o quanto o nosso modelo realmente previu certo, classificou certo no total de resultados. Em todos os valores classificados o quanto ele realmente acertou.
print(accuracy_score(y_teste, predito_knn)), o primeiro modelo é o KNN. Novamente, os primeiros dados a serem colocados na função da acurácia, do score da acurácia é o conjunto Y teste, é o valor real. E o segundo valor é o predito pelo nosso modelo.Vamos verificar e obtivemos um resultado de 0.745, se multiplicarmos por 100 temos 74,53% de acerto. É um valor alto, muito interessante.
Vamos ver os outros modelos, qual entre eles está acertando mais. Agora o Bernoulli, da mesma forma que o modelo KNN vamos mandar imprimir: print(accuracy_score(y_teste, predito_bnb)), vamos verificar. O modelo Bernoulli teve um resultado de acurácia de 0,7549. Novamente, 71,84%, o modelo KNN até agora está ganhando.Se considerarmos a métrica da acurácia o modelo que apresentaríamos para a equipe de vendas seria o modelo KNN. Agora vamos verificar a árvore de decisão, a mesma coisa que os outros modelos, a única coisa que vamos alterar é o modelo, vamos colocar predito_ArvoreDecisao. Vamos mandar imprimir.
O resultado do nosso modelo da árvore de decisão é de 73,70%. Se considerarmos o quanto o nossos modelos acertaram o melhor modelo para classificar os verdadeiros positivos e os verdadeiros negativos é o KNN. 74,53% e é esse modelo que apresentaríamos para a equipe de vendas.

In [58]:
from sklearn.metrics import accuracy_score

In [59]:
#Modelo KNN
print(accuracy_score(y_teste, predito_knn))

0.7453857075248462


In [60]:
#Modelo Bernoulli da Naive Bayes
print(accuracy_score(y_teste, predito_BNb))

0.718409843823947


In [61]:
#Modelo Árvore de decisão
print(accuracy_score(y_teste, predito_ArvoreDecisao))


0.7330809275911027


Métrica de precisão = . A Precisão calcula quantos verdadeiros positivos foram classificados de forma correta, foram preditos de forma correta. Como se calcula isso?Sabemos que os verdadeiros positivos são aqueles que foram realmente preditos como verdadeiro sim, a precisão é calculada da seguinte forma: o total de verdadeiros positivos dividido pelos verdadeiros positivos mais os falsos positivos, "PS = TP/TP + FP".Estamos pegando os verdadeiros positivos e dividindo pelo total de positivos previstos, seja ele correto ou não. Essa é a precisão, cálculo dos positivos corretos.Vamos implementar essa métrica para aplicar aos dados. Novamente, vamos chamar a biblioteca SKLearn e o pacote metrics e agora vamos chamar a função precision_score e chamamos da mesma forma que as outras bibliotecas: from sklearn.metrics import precision_score.Funções também importadas, tudo carregado no nosso notebook, vamos agora mandar ver nossas precisões de cada um dos modelos.
O primeiro modelo é o KNN: print(precision_score(y_teste, predito_knn. Da mesma forma das outras métricas, quais dados aplicamos na função o primeiro é o real e o segundo dado é o predito, classificado pelo nosso modelo.
Vamos ver os nossos resultados e aqui está, para o modelo KNN temos uma precisão de 0.55263, em porcentagem 55,26%. Parece que a precisão dos positivos está menor que a acurácia.Agora vamos verificar o modelo de Bernoulli de Naive Bayes. Novamente, vamos mandar imprimir o nosso score da precisão, print(precision_score(y_teste, predito_BNb)). Vamos ver, a precisão do modelo de Bernoulli também deu 49,73%.
Vamos ver a árvore de decisão. Até agora o modelo KNN é o mais preciso em relação aos positivos. O modelo da árvore de decisão é 52,26%. No caso de escolhermos a métrica de precisão para mostrar para a equipe de vendas, o modelo da árvore de decisão seria o melhor modelo a se apresentar como o relatório, como resultado da classificação.
Olha que curioso, cada uma das métricas apresentaram um modelo como melhor. A acurácia apresentou o KNN, a precisão apresentou o modelo árvore de decisão. Atenção à isso, lembre-se disso.Devemos utilizar as métricas acurácia e precisão, a acurácia é quando queremos a performance geral do modelo.E precisão dentre todas de classe positivo quantas estão corretas.

In [62]:
from sklearn.metrics import precision_score

In [63]:
#Modelo KNN
print(precision_score(y_teste, predito_knn))

0.5526315789473685


In [64]:
#Modelo Bernoulli de Naive Bayes
print(precision_score(y_teste, predito_BNb))

0.49737118822292326


In [65]:
#Modelo de Árvore de decisão
print(precision_score(y_teste, predito_ArvoreDecisao))

0.5226480836236934


O recall também é conhecido como revocação ou sensibilidade. Preste muita atenção, o recall muitas vezes é confundido com a precisão, porque ele vai medir quão bom o nosso modelo está em classificar os resultados realmente positivos.
Vamos ver a fórmula do recall. Verdadeiros positivos, que são aqueles que foram classificados como sim pelo nosso modelo e que são realmente sim, divididos pelos verdadeiros positivos mais os falsos negativos, "RC = TP/TP + FN". Entendeu a diferença?
Aqui, os falsos negativos não deveriam ser positivos? Por isso que essa métrica é considerada aquela que calcula realmente quais os resultados verdadeiramente positivos. Vamos aplicar no nosso modelo e ver qual o resultado disso.
Novamente vamos chamar a biblioteca metrics e agora o recall_store, from sklearn.metrics import recall_score. Funções carregadas no notebook, vamos aplicar o nosso primeiro modelo o KNN: print(recall_score(y_teste, predito_knn)), tendo um resultado de 0,4627 ou em porcentagem 46,27%. É um valor muito alto, muito bom e quanto maior quer dizer que melhor está o modelo em classificar esses valores como sim, o nosso Churn sim.
Vamos agora para o modelo Bernoulli de Naive Bayes. A mesma coisa, print(recall_score(y_teste, predito_BNb)). Já o nosso modelo de Bernoulli foi melhor, ele teve 80,16% de acertos. O nosso modelo está bom em acerta os sins.
Lembrando, que o nosso Churn igual a sim é aquele cliente que realmente saiu da empresa, ele saiu, não faz mais parte, não tem mais contrato ativo, saiu da Alura Voz.
Vamos agora para o modelo final, a árvore de decisão. A mesma coisa dos outros modelos, alterando somente para o predito_ArvoreDecisao. print(recall_score(y_teste, predito_ArvoreDecisao)), tendo o resultado de 50,84%.
Olha que curioso, cada uma das métricas que apresentei para você mostrou que um modelo era melhor do que o outro. Tivemos a acurácia que trouxe o KNN como melhor modelo, tivemos a precisão que trouxe o modelo de árvore de decisão como melhor. E agora, na recall, na sensibilidade o melhor modelo é o Bernoulli de Naive Bayes.

In [66]:
from sklearn.metrics import recall_score

In [69]:
#Modelo KNN
print(recall_score(y_teste, predito_knn))

0.46271186440677964


In [71]:
#Modelo Bernoulli de Naive Bayes
print(recall_score(y_teste, predito_BNb))

0.8016949152542373


In [72]:
#Modelo Árvore de decisão
print(recall_score(y_teste, predito_ArvoreDecisao))

0.5084745762711864


F1 score
Além da acurácia, precisão e recall, podemos extrair da matriz de confusão uma outra métrica conhecida como f1 score, que é uma média harmônica entre o recall e a precisão.O recall e a precisão são grandezas inversamente proporcionais, ou seja, à medida que vai aumentando o recall, por consequência irá diminuir a precisão e vice-versa.

O f1 score é uma métrica para identificar se algum dos valores de recall ou precisão estão baixos, uma vez que não é muito interessante ter um modelo com um alto recall e pouca precisão, ou vice versa. Então, caso sua intenção seja obter um valor equilibrado entre o recall e a precisão, a métrica que precisamos maximizar é o f1 score.

Para calcular, devemos utilizar a fórmula:

alt text: Fórmula: f1 igual a 2 vezes o quociente entre dois termos. O numerador é o produto de precisão e recall. O denominador é a soma entre precisão e recall.

Curva ROC e AUC
Existe ainda uma métrica conhecida como AUC (Area Under the Curve), ou área sob a curva, que pode ser extraída da curva ROC. Essa métrica tem valor máximo de 1 e quanto maior o número mais bem avaliado será o modelo de classificação. Para a construção da curva ROC, precisamos utilizar diferentes pontos de corte para avaliação do modelo de classificação.

É possível criar diferentes matrizes de confusão a partir dos diversos pontos de corte e extrair as métricas de recall (taxa de verdadeiros positivos) e taxa de falsos positivos. Sendo esta última, o valor de falsos positivos dividido pela soma de todos os valores negativos reais. Essas métricas podem ser sumarizadas em uma tabela e serão as coordenadas da curva ROC. Vamos entender como funcionam esses pontos de corte.

Na construção de um modelo de classificação, a predição de uma classe está atrelada a uma probabilidade. Imagine que temos uma variável alvo com duas possibilidades (0 ou 1). Se um modelo classifica uma observação como 1, significa que há uma probabilidade de x% de que aquela observação seja da classe 1.

O ponto de corte é um valor de probabilidade no qual, se a probabilidade de predição for maior que esse valor, atribui-se a observação à classe 1. Se for menor, atribui-se a observação à classe 0. À medida que o ponto de corte varia, os resultados obtidos na classificação se tornam diferentes, fazendo com que o modelo acerte mais de uma classe em troca de errar mais em outra.

Através de um exemplo, ficará evidente como os pontos de corte modificam as métricas da matriz de confusão. Na imagem abaixo estão representados a precisão e o recall. Nela estão definidos 3 pontos de corte em 25%, 50% e 75%, representados pelas setas verticais. Os zeros e uns são os valores reais das classes e a classificação será feita através dos pontos de corte. Os valores à esquerda da seta serão classificados como 0 e os valores à direita serão classificados como 1 pelo modelo.

alt text: Sequência de zeros e uns na ordem: 001010110101. Esta sequência está demarcada por 3 setas, de cima para baixo, dividindo a sequência em 4 partes: 001, 010, 110, 101. Essas setas se conectam a outras 3 setas tracejadas localizadas abaixo da sequência de zeros e uns. As setas tracejadas partem da frase “Diferentes pontos de corte”, localizada na parte inferior. Na parte superior, há 3 valores de precisão e 3 valores de recall para cada ponto de corte na sequência. Sendo o primeiro valor de precisão: 5/9 = 55,5% e recall 5/6 = 83%; o segundo de precisão 4/6 = 66,6% e recall 4/6 = 66,6%; e o terceiro de precisão 2/3 = 66,6% e recall 2/6 = 33,3%.

No primeiro ponto de corte temos 3 valores classificados como 0, à esquerda; e 9 valores como 1, à direita. A precisão é dada por 5/(5+4) = 55,5%, mostrando que 5 valores foram classificados corretamente como 1, dentre 9 valores totais classificados como 1. O recall é dado por 5/(5+1) = 83%, indicando que 5 valores foram classificados corretamente como 1, dentre 6 valores reais 1 no conjunto de dados.

No segundo ponto de corte temos 6 valores classificados como 0 à esquerda; e 6 valores classificados como 1, à direita. A precisão é dada por 4/(4+2) = 66,6%, apontando que 4 valores foram classificados corretamente como 1, dentre 6 valores totais classificados como 1. O recall é dado por 4/(4+2) = 66,6%, demonstrando que 4 valores foram classificados corretamente como 1, dentre 6 valores reais 1 no conjunto de dados. O mesmo raciocínio pode ser aplicado para o último ponto de corte, resultando em valores diferentes para as métricas.

Para cada ponto de corte, uma matriz de confusão pode ser criada e as métricas podem ser extraídas em uma tabela, na qual cada linha representa um ponto de corte com suas respectivas métricas. Desta tabela, pode ser construído o gráfico da curva ROC. Esta curva mostra como o classificador se comporta para diferentes valores de pontos de corte, de acordo com a relação de verdadeiros positivos e falsos positivos.

alt text: Gráfico de linhas. O eixo x representa o False Positive Rate com valores decimais 0.0 a 1.0, de 2.0 em 2.0. O eixo y representa a True Positive Rate, com valores decimais de 0.0 a 1.0, de 2.0 em 2.0. A legenda do gráfico contém uma linha azul representando RandomForestClassifier (AUC: 0.979), uma linha laranja representando DecisionTreeClassifier (AUC: 0.914) e uma estrela representando Youden’s J Statistic. Ambas as linhas iniciam no ponto (0, 0). A linha azul atinge aproximadamente o ponto (0.07, 1) enquanto a laranja atinge aproximadamente o ponto (0.17, 1). Ambas permanecem nos pontos mencionados anteriormente em linha reta até atingir o ponto (1, 1). Nesse ponto, encontram uma linha preta tracejada na diagonal.

Existe uma linha de referência na diagonal do gráfico que corresponde à uma linha de base e representa o caso no qual o classificador identifica aleatoriamente as classes. Mas como podemos interpretar esse gráfico?

Percebemos que a linha representando o classificador RandomForestClassifier cresce rapidamente até atingir o valor máximo de True Positive Rate (o recall). Isso significa que o modelo atinge 100% de classificação correta dos positivos e permanece até atingir o ponto (1, 1) do gráfico. Esse ponto nos diz que o modelo tem 100% de True Positive Rate e 100% de False Positive Rate (taxa de falso negativos), indicando que ele classifica todas as amostras positivas corretamente e todas as amostras que não são positivas foram incorretamente classificadas.

Então, quando o modelo chega no 100% de True Positive Rate e lá permanece até atingir o 100% do False Positive Rate, ele consegue classificar todas as amostras positivas de forma correta independentemente do threshold adotado. Por outro lado, a linha representando o classificador DecisionTreeClassifier demora mais para chegar no 100% de True Positive Rate. Porém, quando chega no valor máximo, permanece igual à do classificador anterior.

Esse pequeno atraso do DecisionTreeClassifier em relação ao RandomForestClassifier resulta em áreas diferentes, que são as AUCs para cada classificador. O primeiro teve uma AUC de 0.914 e o segundo 0.979. Portanto, esse último é o melhor classificador.

Melhor modelo foi a precisão pois Eu escolhi utilizar a precisão. A precisão vai medir quantos valores positivos foram previstos de forma correta com um todo no nosso modelo. Lembrando que os verdadeiros positivos são os sins, é aquele Churn igual a sim. É aquele Churn que precisamos dar atenção, é o Churn que temos que reduzir, são as pessoas que estão deixando a nossa empresa, estamos deixando de lucrar, a Alura Voz está perdendo com esses clientes saindo.
É um valor que temos que estar atentos, o nosso modelo tem que saber prever bem esses valores para podermos criar ações, tomar decisões em cima desses clientes.
Eu escolhi utilizar a precisão. Porém, outra métrica muito interessante seria a recall, sensibilidade porque agora sim, ele mede o verdadeiro positivo, seria até melhor que a precisão. Contudo, por escolha que eu achei mais interessante para vocês é a precisão.
Com isso concluímos que para escolher a melhor métrica para aplicar ao nosso modelo, para obter o melhor resultado, até para apresentar em seus relatórios, nas suas entregas, depende do dado que você está trabalhando, depende do problema que você quer solucionar.
Por isso, muita atenção. Entenda bem o seu problema, entenda bem a solução que você tem que correr atrás porque é a partir daí que você vai saber mudar todo o seu processo de modelagem, criação e validação de resultados.
Vamos verificar e escolher o melhor modelo. Vamos fazer um print de todos os resultados: print(), eu coloquei entre aspas 'Modelo KNN:', para indicar qual é cada um desses resultados, print('Modelo KNN:', precision_score(y_teste, predito_knn)).
E aí fazemos um "Ctrl + C" "Ctrl + V" aqui e só muda também os modelos para predito_BNb e predito_ArvoreDecisao e os nomes também Modelo Bernoulli de Naive Bayes e Modelo Árvore de Decisão. Então:Rodamos. Se você estiver atento vai perceber que o melhor modelo para a nossa equipe de vendas é o modelo KNN, que apresentou 55,26% de acerto. é um valor muito bom, muito interessante, entre todos os outros foi o melhor.
O Àrvode de decisão chegou bem perto, com 52,26 % e o Bernoulli de Naive Bayes talvez precisamos melhorar um pouco mais, porque acerto 49,73%. Não é um resultado ruim, mas a Árvore de Decisão foi melhor.

In [77]:
print('Modelo KNN:', precision_score(y_teste, predito_knn)) 
print('Modelo Bernoulli de Naive Bayes:', precision_score(y_teste, predito_BNb))
print('Modelo Àrvore de Decisão:', precision_score(y_teste, predito_ArvoreDecisao))


Modelo KNN: 0.5526315789473685
Modelo Bernoulli de Naive Bayes: 0.49737118822292326
Modelo Àrvore de Decisão: 0.5226480836236934
